FROM debian:jessie

RUN apt-get -qq update && apt-get install --no-install-recommends -y curl ca-certificates sudo build-essential libcurl4-gnutls-dev
RUN curl -L https://toolbelt.treasuredata.com/sh/install-debian-jessie-td-agent3.sh | sh
RUN /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch fluent-plugin-record-reformer

EXPOSE 24224

# td-agentコマンドは、以下のオプションを指定できる
# https://docs.fluentd.org/deployment/command-line-option
CMD exec td-agent -c /fluentd/etc/forwarder/$FLUENTD_CONF
