version: "3.0"

services:
  nginx:
    image: nginx:1.17.9
    volumes:
      # ローカルのnginx設定をコンテンに設定する
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      # fluentdに読みこますために、ログをローカルのnginxlogディレクトリに同期
      - nginxlog:/var/log/nginx
    ports:
      - 80:80

volumes:
  nginxlog:
    driver: local
