version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_play
      # envでJVMoptionを設定する
  nginx:
    image: nginx:1.17.9
    volumes:
      # ローカルのnginx設定をコンテンに設定する
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      # fluentdに読みこますために、ログをローカルのnginxlogディレクトリに同期
      - nginxlog:/var/log/nginx
    ports:
      - 80:80
  fluentd-forwarder:
    build:
      context: .
      dockerfile: Dockerfile_fluentd_forwarder
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - nginxlog:/var/log/nginx:ro
      - ./fluentd/etc/forwarder:/fluentd/etc/forwarder

volumes:
  nginxlog:
    driver: local
