apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  # cluster内からのみ疎通性のあるIPが割り当てられる
  # cluster内でのロードバランサーを作成する
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: sample-app
